# -*- coding: utf-8 -*-
"""RL(Online Decision Transformer ODT)

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/17zXzue5CgUcQP6VaYE1A9iukRheeqHkY
"""

# Commented out IPython magic to ensure Python compatibility.
!git clone https://github.com/facebookresearch/online-dt.git
# %cd online-dt

!apt-get install -y libosmesa6-dev libgl1-mesa-glx libglfw3 patchelf
!pip install mujoco==2.3.7
import os
os.environ['MUJOCO_GL'] = 'osmesa'

!pip install mujoco==2.3.0
!pip install gym==0.21.0 torch transformers wandb tensorboard
!pip install git+https://github.com/Farama-Foundation/d4rl@master#egg=d4rl

!apt-get install -y python3.10 python3.10-venv python3.10-dev
!python3.10 -m ensurepip
!python3.10 -m pip install --upgrade pip

!python3.10 -m pip install torch transformers wandb tensorboard
!python3.10 -m pip install gym==0.21.0
!apt-get install -y libosmesa6-dev libgl1-mesa-glx libglfw3 patchelf
!python3.10 -m pip install mujoco==2.3.7 mujoco-py==2.1.2.14
!python3.10 -m pip install git+https://github.com/Farama-Foundation/d4rl@master#egg=d4rl

import subprocess
result = subprocess.run(['python3.10', '-c', 'import d4rl; print("✅ d4rl working!")'], capture_output=True, text=True)
print(result.stdout)
print(result.stderr)

!wget -q https://repo.anaconda.com/miniconda/Miniconda3-latest-Linux-x86_64.sh
!bash Miniconda3-latest-Linux-x86_64.sh -b -p /content/miniconda
import os
os.environ['PATH'] = '/content/miniconda/bin:' + os.environ['PATH']

!conda create -n odt python=3.10 -y

!/content/miniconda/bin/conda tos accept --override-channels --channel https://repo.anaconda.com/pkgs/main
!/content/miniconda/bin/conda tos accept --override-channels --channel https://repo.anaconda.com/pkgs/r

!/content/miniconda/bin/conda create -n odt python=3.10 -y

!apt-get install -y libosmesa6-dev libgl1-mesa-glx libglfw3 patchelf
!/content/miniconda/envs/odt/bin/pip install torch transformers wandb tensorboard
!/content/miniconda/envs/odt/bin/pip install gym==0.21.0
!/content/miniconda/envs/odt/bin/pip install mujoco==2.3.7
!/content/miniconda/envs/odt/bin/pip install git+https://github.com/Farama-Foundation/d4rl@master#egg=d4rl

import os
os.environ['MUJOCO_GL'] = 'osmesa'

!/content/miniconda/envs/odt/bin/python -c "import os; os.environ['MUJOCO_GL'] = 'osmesa'; import d4rl; import gym; print('d4rl and gym working!')"

# Commented out IPython magic to ensure Python compatibility.
import os
os.environ['MUJOCO_GL'] = 'osmesa'

# %cd /content/online-dt

!/content/miniconda/envs/odt/bin/python main.py \
  --env hopper-medium-v2 \
  --dataset medium \
  --max_iters 2 \
  --num_steps_per_iter 100 \
  --num_eval_episodes 1

# Commented out IPython magic to ensure Python compatibility.
import os
os.environ['MUJOCO_GL'] = 'osmesa'

# %cd /content/online-dt

!/content/miniconda/envs/odt/bin/python main.py \
  --env hopper-medium-v2 \
  --dataset medium \
  --max_iters 2 \
  --num_steps_per_iter 100 \
  --num_eval_episodes 1 \
  2>&1

# Commented out IPython magic to ensure Python compatibility.
# %cd /content/online-dt
!/content/miniconda/envs/odt/bin/python main.py --help 2>&1

!head -50 /content/online-dt/main.py

!/content/miniconda/envs/odt/bin/pip install stable-baselines3

# Commented out IPython magic to ensure Python compatibility.
# %cd /content/online-dt
!/content/miniconda/envs/odt/bin/python main.py --env hopper-medium-v2 --dataset medium --max_iters 2 --num_steps_per_iter 100 --num_eval_episodes 1 2>&1 | tail -50

!tail -100 /content/online-dt/main.py

# Commented out IPython magic to ensure Python compatibility.
# %cd /content/online-dt
!/content/miniconda/envs/odt/bin/python main.py \
  --env hopper-medium-v2 \
  --max_pretrain_iters 1 \
  --num_updates_per_pretrain_iter 100 \
  --max_online_iters 10 \
  --num_online_rollouts 1 \
  --num_eval_episodes 1 \
  --device cpu \
  --log_to_tb False 2>&1 | tail -100

import subprocess
result = subprocess.run(
    ['/content/miniconda/envs/odt/bin/python', 'main.py',
     '--device', 'cpu',
     '--log_to_tb', 'False',
     '--max_pretrain_iters', '1',
     '--num_updates_per_pretrain_iter', '10',
     '--max_online_iters', '0',
     '--num_eval_episodes', '1'],
    cwd='/content/online-dt',
    capture_output=True,
    text=True,
    timeout=300
)
print("STDOUT:", result.stdout)
print("STDERR:", result.stderr)

!/content/miniconda/envs/odt/bin/pip install numpy==1.24.0

import subprocess
result = subprocess.run(
    ['/content/miniconda/envs/odt/bin/python', 'main.py',
     '--device', 'cpu',
     '--log_to_tb', 'False',
     '--max_pretrain_iters', '1',
     '--num_updates_per_pretrain_iter', '10',
     '--max_online_iters', '0',
     '--num_eval_episodes', '1'],
    cwd='/content/online-dt',
    capture_output=True,
    text=True,
    timeout=300
)
print("STDOUT:", result.stdout[-3000:])
print("STDERR:", result.stderr[-3000:])

test_code = """
import sys
sys.path.insert(0, '/content/online-dt')
import os
os.environ['MUJOCO_GL'] = 'osmesa'
os.chdir('/content/online-dt')
import traceback
try:
    import gym
    import d4rl
    env = gym.make('hopper-medium-v2')
    print('ENV OK:', env)
except Exception as e:
    traceback.print_exc()
"""
with open('/content/test_env.py', 'w') as f:
    f.write(test_code)
print("File created!")

!/content/miniconda/envs/odt/bin/python /content/test_env.py 2>&1

!/content/miniconda/envs/odt/bin/pip install numpy==1.23.5 --force-reinstall 2>&1 | tail -5

!/content/miniconda/envs/odt/bin/python /content/test_env.py 2>&1

test_code2 = """
import sys
sys.path.insert(0, '/content/online-dt')
import os
os.environ['MUJOCO_GL'] = 'osmesa'
os.chdir('/content/online-dt')

print("Step 1: importing gym...")
import gym
print("Step 2: gym imported!")

print("Step 3: importing d4rl...")
import d4rl
print("Step 4: d4rl imported!")

print("Step 5: making env...")
env = gym.make('hopper-medium-v2')
print("Step 6: ENV OK!")
"""
with open('/content/test2.py', 'w') as f:
    f.write(test_code2)

!/content/miniconda/envs/odt/bin/python /content/test2.py 2>&1

!/content/miniconda/envs/odt/bin/pip install gym==0.23.1 --force-reinstall 2>&1 | tail -5

!/content/miniconda/envs/odt/bin/python /content/test2.py 2>&1

test_code3 = """
import sys
sys.path.insert(0, '/content/online-dt')
import os
os.environ['MUJOCO_GL'] = 'osmesa'

print("importing d4rl submodules one by one...")
try:
    import d4rl.locomotion
    print("locomotion OK")
except Exception as e:
    print("locomotion FAILED:", e)

try:
    import d4rl.kitchen
    print("kitchen OK")
except Exception as e:
    print("kitchen FAILED:", e)

try:
    import d4rl.gym_mujoco
    print("gym_mujoco OK")
except Exception as e:
    print("gym_mujoco FAILED:", e)
"""
with open('/content/test3.py', 'w') as f:
    f.write(test_code3)

!/content/miniconda/envs/odt/bin/python /content/test3.py 2>&1

test_code4 = """
import sys
sys.path.insert(0, '/content/online-dt')
import os
os.environ['MUJOCO_GL'] = 'osmesa'

try:
    import d4rl.locomotion
    print("locomotion OK")
except SystemExit as e:
    print("SystemExit:", e)
except BaseException as e:
    print("BaseException:", type(e), e)
"""
with open('/content/test4.py', 'w') as f:
    f.write(test_code4)

!/content/miniconda/envs/odt/bin/python /content/test4.py 2>&1

!/content/miniconda/envs/odt/bin/pip install mujoco-py==2.1.2.14 2>&1 | tail -10

import os
os.makedirs('/root/.mujoco', exist_ok=True)

!/content/miniconda/envs/odt/bin/python -c "import mujoco_py; print(mujoco_py.__file__)"

import os

!wget -q https://mujoco.org/download/mujoco210-linux-x86_64.tar.gz
!tar -xzf mujoco210-linux-x86_64.tar.gz
!mkdir -p /root/.mujoco
!mv mujoco210 /root/.mujoco/mujoco210

os.environ['MUJOCO_PY_MUJOCO_PATH'] = '/root/.mujoco/mujoco210'
os.environ['LD_LIBRARY_PATH'] = '/root/.mujoco/mujoco210/bin'

print("MuJoCo installed!")

!/content/miniconda/envs/odt/bin/python -c "import mujoco_py; print('mujoco_py OK!')" 2>&1

!/content/miniconda/envs/odt/bin/pip install cython==0.29.37 --force-reinstall 2>&1 | tail -5

import os
os.environ['MUJOCO_PY_MUJOCO_PATH'] = '/root/.mujoco/mujoco210'
os.environ['LD_LIBRARY_PATH'] = '/root/.mujoco/mujoco210/bin'

!/content/miniconda/envs/odt/bin/python -c "import mujoco_py; print('mujoco_py OK!')" 2>&1

# Commented out IPython magic to ensure Python compatibility.
import os
os.environ['MUJOCO_PY_MUJOCO_PATH'] = '/root/.mujoco/mujoco210'
os.environ['LD_LIBRARY_PATH'] = '/root/.mujoco/mujoco210/bin'
os.environ['MUJOCO_GL'] = 'osmesa'

# %cd /content/online-dt

!/content/miniconda/envs/odt/bin/python main.py \
  --env hopper-medium-v2 \
  --max_pretrain_iters 1 \
  --num_updates_per_pretrain_iter 100 \
  --max_online_iters 10 \
  --num_online_rollouts 1 \
  --num_eval_episodes 1 \
  --device cpu \
  --log_to_wb False 2>&1

import os
os.environ['MUJOCO_PY_MUJOCO_PATH'] = '/root/.mujoco/mujoco210'
os.environ['LD_LIBRARY_PATH'] = '/root/.mujoco/mujoco210/bin'
os.environ['MUJOCO_GL'] = 'osmesa'

import subprocess
result = subprocess.run(
    ['/content/miniconda/envs/odt/bin/python', 'main.py',
     '--env', 'hopper-medium-v2',
     '--max_pretrain_iters', '1',
     '--num_updates_per_pretrain_iter', '100',
     '--max_online_iters', '10',
     '--num_online_rollouts', '1',
     '--num_eval_episodes', '1',
     '--device', 'cpu',
     '--log_to_wb', 'False'],
    cwd='/content/online-dt',
    capture_output=True,
    text=True,
    timeout=600,
    env={**os.environ}
)
print("STDOUT:", result.stdout[-3000:])
print("STDERR:", result.stderr[-3000:])

import os
os.environ['MUJOCO_PY_MUJOCO_PATH'] = '/root/.mujoco/mujoco210'
os.environ['LD_LIBRARY_PATH'] = '/root/.mujoco/mujoco210/bin'
os.environ['MUJOCO_GL'] = 'osmesa'

import subprocess
result = subprocess.run(
    ['/content/miniconda/envs/odt/bin/python', '/content/test2.py'],
    capture_output=True,
    text=True,
    timeout=120,
    env={**os.environ}
)
print("STDOUT:", result.stdout)
print("STDERR:", result.stderr[-2000:])
print("Return code:", result.returncode)

import os
os.environ['MUJOCO_PY_MUJOCO_PATH'] = '/root/.mujoco/mujoco210'
os.environ['LD_LIBRARY_PATH'] = '/root/.mujoco/mujoco210/bin'
os.environ['MUJOCO_GL'] = 'osmesa'

import subprocess
result = subprocess.run(
    ['/content/miniconda/envs/odt/bin/python', 'main.py',
     '--env', 'hopper-medium-v2',
     '--max_pretrain_iters', '1',
     '--num_updates_per_pretrain_iter', '100',
     '--max_online_iters', '10',
     '--num_online_rollouts', '1',
     '--num_eval_episodes', '1',
     '--device', 'cpu',
     '--log_to_wb', 'False'],
    cwd='/content/online-dt',
    capture_output=True,
    text=True,
    timeout=600,
    env={**os.environ}
)
print("STDOUT:", result.stdout)
print("STDERR:", result.stderr[-2000:])
print("Return code:", result.returncode)

import os
os.environ['MUJOCO_PY_MUJOCO_PATH'] = '/root/.mujoco/mujoco210'
os.environ['LD_LIBRARY_PATH'] = '/root/.mujoco/mujoco210/bin'
os.environ['MUJOCO_GL'] = 'osmesa'
os.environ['MPLBACKEND'] = 'Agg'

import subprocess
result = subprocess.run(
    ['/content/miniconda/envs/odt/bin/python', 'main.py',
     '--env', 'hopper-medium-v2',
     '--max_pretrain_iters', '1',
     '--num_updates_per_pretrain_iter', '100',
     '--max_online_iters', '10',
     '--num_online_rollouts', '1',
     '--num_eval_episodes', '1',
     '--device', 'cpu',
     '--log_to_wb', 'False'],
    cwd='/content/online-dt',
    capture_output=True,
    text=True,
    timeout=600,
    env={**os.environ}
)
print("STDOUT:", result.stdout)
print("STDERR:", result.stderr[-2000:])
print("Return code:", result.returncode)

!/content/miniconda/envs/odt/bin/pip install setuptools==68.0.0 --force-reinstall 2>&1 | tail -5

import os
os.environ['MUJOCO_PY_MUJOCO_PATH'] = '/root/.mujoco/mujoco210'
os.environ['LD_LIBRARY_PATH'] = '/root/.mujoco/mujoco210/bin'
os.environ['MUJOCO_GL'] = 'osmesa'
os.environ['MPLBACKEND'] = 'Agg'

import subprocess
result = subprocess.run(
    ['/content/miniconda/envs/odt/bin/python', 'main.py',
     '--env', 'hopper-medium-v2',
     '--max_pretrain_iters', '1',
     '--num_updates_per_pretrain_iter', '100',
     '--max_online_iters', '10',
     '--num_online_rollouts', '1',
     '--num_eval_episodes', '1',
     '--device', 'cpu',
     '--log_to_wb', 'False'],
    cwd='/content/online-dt',
    capture_output=True,
    text=True,
    timeout=600,
    env={**os.environ}
)
print("STDOUT:", result.stdout)
print("STDERR:", result.stderr[-3000:])
print("Return code:", result.returncode)

import os
os.environ['MUJOCO_PY_MUJOCO_PATH'] = '/root/.mujoco/mujoco210'
os.environ['LD_LIBRARY_PATH'] = '/root/.mujoco/mujoco210/bin'
os.environ['MUJOCO_GL'] = 'osmesa'
os.environ['MPLBACKEND'] = 'Agg'

import subprocess
result = subprocess.run(
    ['/content/miniconda/envs/odt/bin/python', 'main.py',
     '--env', 'hopper-medium-v2',
     '--max_pretrain_iters', '1',
     '--num_updates_per_pretrain_iter', '100',
     '--max_online_iters', '10',
     '--num_online_rollouts', '1',
     '--num_eval_episodes', '1',
     '--device', 'cpu',
     '--log_to_wb', 'False'],
    cwd='/content/online-dt',
    capture_output=True,
    text=True,
    timeout=600,
    env={**os.environ}
)
print("STDOUT:", result.stdout)
print("STDERR:", result.stderr)
print("Return code:", result.returncode)

print("Return code:", result.returncode)

content = open('/content/online-dt/main.py').read()
content = content.replace(
    'from stable_baselines3.common.vec_env import SubprocVecEnv',
    'from stable_baselines3.common.vec_env import SubprocVecEnv\nimport warnings\nwarnings.filterwarnings("ignore")'
)
open('/content/online-dt/main.py', 'w').write(content)
print("Done!")

!/content/miniconda/envs/odt/bin/pip install numpy==1.23.5 --force-reinstall 2>&1 | tail -5

import os
os.environ['MUJOCO_PY_MUJOCO_PATH'] = '/root/.mujoco/mujoco210'
os.environ['LD_LIBRARY_PATH'] = '/root/.mujoco/mujoco210/bin:/usr/lib/x86_64-linux-gnu'
os.environ['MUJOCO_GL'] = 'osmesa'
os.environ['MPLBACKEND'] = 'Agg'
os.environ['LD_PRELOAD'] = '/usr/lib/x86_64-linux-gnu/libGLEW.so'

import subprocess
result = subprocess.run(
    ['/content/miniconda/envs/odt/bin/python', 'main.py',
     '--env', 'hopper-medium-v2',
     '--max_pretrain_iters', '1',
     '--num_updates_per_pretrain_iter', '100',
     '--max_online_iters', '10',
     '--num_online_rollouts', '1',
     '--num_eval_episodes', '1',
     '--device', 'cpu',
     '--log_to_wb', 'False'],
    cwd='/content/online-dt',
    capture_output=True,
    text=True,
    timeout=600,
    env={**os.environ}
)
print("STDOUT:", result.stdout)
print("STDERR:", result.stderr[-3000:])
print("Return code:", result.returncode)

!/content/miniconda/envs/odt/bin/pip install git+https://github.com/carlosluis/stable-baselines3@fix_tests 2>&1 | tail -5

import os
os.environ['MUJOCO_PY_MUJOCO_PATH'] = '/root/.mujoco/mujoco210'
os.environ['LD_LIBRARY_PATH'] = '/root/.mujoco/mujoco210/bin'
os.environ['MUJOCO_GL'] = 'egl'
os.environ['MPLBACKEND'] = 'Agg'
os.environ['PYOPENGL_PLATFORM'] = 'egl'

!apt-get install -y libegl1-mesa-dev 2>&1 | tail -3

import subprocess
result = subprocess.run(
    ['/content/miniconda/envs/odt/bin/python', 'main.py',
     '--env', 'hopper-medium-v2',
     '--max_pretrain_iters', '1',
     '--num_updates_per_pretrain_iter', '100',
     '--max_online_iters', '10',
     '--num_online_rollouts', '1',
     '--num_eval_episodes', '1',
     '--device', 'cpu',
     '--log_to_wb', 'False'],
    cwd='/content/online-dt',
    capture_output=True,
    text=True,
    timeout=600,
    env={**os.environ}
)
print("STDOUT:", result.stdout)
print("STDERR:", result.stderr[-3000:])
print("Return code:", result.returncode)

d4rl_init = '/content/miniconda/envs/odt/lib/python3.10/site-packages/d4rl/__init__.py'
content = open(d4rl_init).read()
content = content.replace('import d4rl.locomotion', '#import d4rl.locomotion')
content = content.replace('import d4rl.kitchen', '#import d4rl.kitchen')
content = content.replace('import d4rl.gym_mujoco', '#import d4rl.gym_mujoco')
content = content.replace('import d4rl.gym_minigrid', '#import d4rl.gym_minigrid')
open(d4rl_init, 'w').write(content)
print("Done! d4rl patched!")

import os
os.environ['MUJOCO_PY_MUJOCO_PATH'] = '/root/.mujoco/mujoco210'
os.environ['LD_LIBRARY_PATH'] = '/root/.mujoco/mujoco210/bin'
os.environ['MUJOCO_GL'] = 'osmesa'
os.environ['MPLBACKEND'] = 'Agg'

import subprocess
result = subprocess.run(
    ['/content/miniconda/envs/odt/bin/python', 'main.py',
     '--env', 'hopper-medium-v2',
     '--max_pretrain_iters', '1',
     '--num_updates_per_pretrain_iter', '100',
     '--max_online_iters', '10',
     '--num_online_rollouts', '1',
     '--num_eval_episodes', '1',
     '--device', 'cpu',
     '--log_to_wb', 'False'],
    cwd='/content/online-dt',
    capture_output=True,
    text=True,
    timeout=600,
    env={**os.environ}
)
print("STDOUT:", result.stdout)
print("STDERR:", result.stderr[-3000:])
print("Return code:", result.returncode)

d4rl_init = '/content/miniconda/envs/odt/lib/python3.10/site-packages/d4rl/__init__.py'
content = open(d4rl_init).read()
print(content[:500])

d4rl_init = '/content/miniconda/envs/odt/lib/python3.10/site-packages/d4rl/__init__.py'
content = open(d4rl_init).read()

# replace all imports with try/except
new_imports = """
try:
    import d4rl.locomotion
except Exception:
    pass
try:
    import d4rl.kitchen
except Exception:
    pass
try:
    import d4rl.gym_mujoco
except Exception:
    pass
try:
    import d4rl.gym_minigrid
except Exception:
    pass
"""

# find where imports start and replace
import re
content = re.sub(r'(try:.*?except ImportError.*?\n)', new_imports, content, flags=re.DOTALL)
open(d4rl_init, 'w').write(content)
print("Patched!")
print(open(d4rl_init).read()[:800])

d4rl_init = '/content/miniconda/envs/odt/lib/python3.10/site-packages/d4rl/__init__.py'

# read full content
content = open(d4rl_init).read()

# find the problematic lines and replace
lines = content.split('\n')
new_lines = []
skip_next = False
for line in lines:
    if 'import d4rl.locomotion' in line or \
       'import d4rl.kitchen' in line or \
       'import d4rl.gym_mujoco' in line or \
       'import d4rl.gym_minigrid' in line:
        new_lines.append('    pass  # ' + line.strip())
    else:
        new_lines.append(line)

open(d4rl_init, 'w').write('\n'.join(new_lines))
print("Patched!")

# verify
!/content/miniconda/envs/odt/bin/python -c "import d4rl; print('d4rl OK!')" 2>&1

import os
# LD_PRELOAD সরিয়ে দাও
if 'LD_PRELOAD' in os.environ:
    del os.environ['LD_PRELOAD']

os.environ['MUJOCO_PY_MUJOCO_PATH'] = '/root/.mujoco/mujoco210'
os.environ['LD_LIBRARY_PATH'] = '/root/.mujoco/mujoco210/bin'
os.environ['MUJOCO_GL'] = 'osmesa'
os.environ['MPLBACKEND'] = 'Agg'

import subprocess
result = subprocess.run(
    ['/content/miniconda/envs/odt/bin/python', 'main.py',
     '--env', 'hopper-medium-v2',
     '--max_pretrain_iters', '1',
     '--num_updates_per_pretrain_iter', '100',
     '--max_online_iters', '10',
     '--num_online_rollouts', '1',
     '--num_eval_episodes', '1',
     '--device', 'cpu',
     '--log_to_wb', 'False'],
    cwd='/content/online-dt',
    capture_output=True,
    text=True,
    timeout=600,
    env={**os.environ}
)
print("STDOUT:", result.stdout)
print("STDERR:", result.stderr[-3000:])
print("Return code:", result.returncode)

print("Return code:", result.returncode)
print("STDOUT length:", len(result.stdout))
print("STDERR length:", len(result.stderr))

print(result.stderr)

test_code = """
import sys
sys.path.insert(0, '/content/online-dt')
import os
os.environ['MUJOCO_PY_MUJOCO_PATH'] = '/root/.mujoco/mujoco210'
os.environ['LD_LIBRARY_PATH'] = '/root/.mujoco/mujoco210/bin'
os.environ['MUJOCO_GL'] = 'osmesa'
os.environ['MPLBACKEND'] = 'Agg'

print("1. torch...")
from torch.utils.tensorboard import SummaryWriter
print("2. OK")
import argparse, pickle, random, time, gym, d4rl, torch, numpy as np
print("3. OK")
import utils
print("4. OK")
from replay_buffer import ReplayBuffer
print("5. OK")
from lamb import Lamb
print("6. OK")
from stable_baselines3.common.vec_env import SubprocVecEnv
print("7. OK")
from data import create_dataloader
print("8. OK")
from decision_transformer.models.decision_transformer import DecisionTransformer
print("9. OK")
from evaluation import create_vec_eval_episodes_fn, vec_evaluate_episode_rtg
print("10. OK")
from trainer import SequenceTrainer
print("11. OK")
from logger import Logger
print("12. ALL IMPORTS OK!")
"""
with open('/content/test_imports.py', 'w') as f:
    f.write(test_code)

import os, subprocess
env = {**os.environ}
env['MUJOCO_PY_MUJOCO_PATH'] = '/root/.mujoco/mujoco210'
env['LD_LIBRARY_PATH'] = '/root/.mujoco/mujoco210/bin'
env['MUJOCO_GL'] = 'osmesa'
env['MPLBACKEND'] = 'Agg'
if 'LD_PRELOAD' in env:
    del env['LD_PRELOAD']

result = subprocess.run(
    ['/content/miniconda/envs/odt/bin/python', '/content/test_imports.py'],
    capture_output=True, text=True, timeout=120, env=env
)
print("STDOUT:", result.stdout)
print("STDERR:", result.stderr[-2000:])
print("Return code:", result.returncode)

test_code = """
import sys
sys.path.insert(0, '/content/online-dt')
import os
os.environ['MUJOCO_GL'] = 'osmesa'
os.environ['MPLBACKEND'] = 'Agg'

print("importing data.py...")
import traceback
try:
    from data import create_dataloader
    print("data.py OK!")
except Exception as e:
    traceback.print_exc()
except BaseException as e:
    print("BaseException:", type(e), e)
    traceback.print_exc()
"""
with open('/content/test_data.py', 'w') as f:
    f.write(test_code)

import os, subprocess
env = {**os.environ}
env['MUJOCO_PY_MUJOCO_PATH'] = '/root/.mujoco/mujoco210'
env['LD_LIBRARY_PATH'] = '/root/.mujoco/mujoco210/bin'
env['MUJOCO_GL'] = 'osmesa'
env['MPLBACKEND'] = 'Agg'
if 'LD_PRELOAD' in env:
    del env['LD_PRELOAD']

result = subprocess.run(
    ['/content/miniconda/envs/odt/bin/python', '/content/test_data.py'],
    capture_output=True, text=True, timeout=120, env=env
)
print("STDOUT:", result.stdout)
print("STDERR:", result.stderr[-2000:])
print("Return code:", result.returncode)

test_code = """
import sys
sys.path.insert(0, '/content/online-dt')
import os
os.environ['MUJOCO_GL'] = 'osmesa'
os.environ['MPLBACKEND'] = 'Agg'

print("8. data OK")
from data import create_dataloader

print("9. DecisionTransformer...")
from decision_transformer.models.decision_transformer import DecisionTransformer
print("9. OK")

print("10. evaluation...")
from evaluation import create_vec_eval_episodes_fn, vec_evaluate_episode_rtg
print("10. OK")

print("11. trainer...")
from trainer import SequenceTrainer
print("11. OK")

print("12. logger...")
from logger import Logger
print("12. ALL OK!")
"""
with open('/content/test_imports2.py', 'w') as f:
    f.write(test_code)

import os, subprocess
env = {**os.environ}
env['MUJOCO_PY_MUJOCO_PATH'] = '/root/.mujoco/mujoco210'
env['LD_LIBRARY_PATH'] = '/root/.mujoco/mujoco210/bin'
env['MUJOCO_GL'] = 'osmesa'
env['MPLBACKEND'] = 'Agg'
if 'LD_PRELOAD' in env: del env['LD_PRELOAD']

result = subprocess.run(
    ['/content/miniconda/envs/odt/bin/python', '/content/test_imports2.py'],
    capture_output=True, text=True, timeout=120, env=env
)
print("STDOUT:", result.stdout)
print("STDERR:", result.stderr[-2000:])
print("Return code:", result.returncode)

!/content/miniconda/envs/odt/bin/pip install transformers==4.30.0 --force-reinstall 2>&1 | tail -5

import os, subprocess
env = {**os.environ}
env['MUJOCO_PY_MUJOCO_PATH'] = '/root/.mujoco/mujoco210'
env['LD_LIBRARY_PATH'] = '/root/.mujoco/mujoco210/bin'
env['MUJOCO_GL'] = 'osmesa'
env['MPLBACKEND'] = 'Agg'
if 'LD_PRELOAD' in env: del env['LD_PRELOAD']

result = subprocess.run(
    ['/content/miniconda/envs/odt/bin/python', 'main.py',
     '--env', 'hopper-medium-v2',
     '--max_pretrain_iters', '1',
     '--num_updates_per_pretrain_iter', '100',
     '--max_online_iters', '10',
     '--num_online_rollouts', '1',
     '--num_eval_episodes', '1',
     '--device', 'cpu',
     '--log_to_wb', 'False'],
    cwd='/content/online-dt',
    capture_output=True, text=True, timeout=600, env=env
)
print("STDOUT:", result.stdout)
print("STDERR:", result.stderr[-3000:])
print("Return code:", result.returncode)

import os, subprocess
env = {**os.environ}
env['MUJOCO_PY_MUJOCO_PATH'] = '/root/.mujoco/mujoco210'
env['LD_LIBRARY_PATH'] = '/root/.mujoco/mujoco210/bin'
env['MUJOCO_GL'] = 'osmesa'
env['MPLBACKEND'] = 'Agg'
if 'LD_PRELOAD' in env: del env['LD_PRELOAD']

result = subprocess.run(
    ['/content/miniconda/envs/odt/bin/python', '/content/test_imports2.py'],
    capture_output=True, text=True, timeout=120, env=env
)
print("STDOUT:", result.stdout)
print("STDERR:", result.stderr[-2000:])
print("Return code:", result.returncode)

!/content/miniconda/envs/odt/bin/pip install tokenizers==0.10.3 2>&1 | tail -5
!/content/miniconda/envs/odt/bin/pip install transformers==4.11.0 --no-deps 2>&1 | tail -5

# trajectory_gpt2.py থেকে tokenizer_class argument সরিয়ে দাও
content = open('/content/online-dt/decision_transformer/models/trajectory_gpt2.py').read()
content = content.replace(', tokenizer_class="GPT2Tokenizer"', '')
content = content.replace('tokenizer_class="GPT2Tokenizer",', '')
content = content.replace('tokenizer_class="GPT2Tokenizer"', '')
open('/content/online-dt/decision_transformer/models/trajectory_gpt2.py', 'w').write(content)
print("Fixed!")

!/content/miniconda/envs/odt/bin/pip install transformers==4.26.0 --no-deps 2>&1 | tail -5

import os, subprocess
env = {**os.environ}
env['MUJOCO_PY_MUJOCO_PATH'] = '/root/.mujoco/mujoco210'
env['LD_LIBRARY_PATH'] = '/root/.mujoco/mujoco210/bin'
env['MUJOCO_GL'] = 'osmesa'
env['MPLBACKEND'] = 'Agg'
if 'LD_PRELOAD' in env: del env['LD_PRELOAD']

result = subprocess.run(
    ['/content/miniconda/envs/odt/bin/python', '/content/test_imports2.py'],
    capture_output=True, text=True, timeout=120, env=env
)
print("STDOUT:", result.stdout)
print("STDERR:", result.stderr[-2000:])
print("Return code:", result.returncode)

content = open('/content/online-dt/decision_transformer/models/trajectory_gpt2.py').read()

# find the problematic decorator and fix it
import re
content = re.sub(r'@add_code_sample_docstrings\([^)]*\)', '@add_code_sample_docstrings()', content)

open('/content/online-dt/decision_transformer/models/trajectory_gpt2.py', 'w').write(content)
print("Fixed!")

# verify
import os, subprocess
env = {**os.environ}
env['MUJOCO_PY_MUJOCO_PATH'] = '/root/.mujoco/mujoco210'
env['LD_LIBRARY_PATH'] = '/root/.mujoco/mujoco210/bin'
env['MUJOCO_GL'] = 'osmesa'
env['MPLBACKEND'] = 'Agg'
if 'LD_PRELOAD' in env: del env['LD_PRELOAD']

result = subprocess.run(
    ['/content/miniconda/envs/odt/bin/python', '/content/test_imports2.py'],
    capture_output=True, text=True, timeout=120, env=env
)
print("STDOUT:", result.stdout)
print("STDERR:", result.stderr[-2000:])
print("Return code:", result.returncode)

import os, subprocess
env = {**os.environ}
env['MUJOCO_PY_MUJOCO_PATH'] = '/root/.mujoco/mujoco210'
env['LD_LIBRARY_PATH'] = '/root/.mujoco/mujoco210/bin'
env['MUJOCO_GL'] = 'osmesa'
env['MPLBACKEND'] = 'Agg'
if 'LD_PRELOAD' in env: del env['LD_PRELOAD']

result = subprocess.run(
    ['/content/miniconda/envs/odt/bin/python', 'main.py',
     '--env', 'hopper-medium-v2',
     '--max_pretrain_iters', '1',
     '--num_updates_per_pretrain_iter', '100',
     '--max_online_iters', '10',
     '--num_online_rollouts', '1',
     '--num_eval_episodes', '1',
     '--device', 'cpu',
     '--log_to_wb', 'False'],
    cwd='/content/online-dt',
    capture_output=True, text=True, timeout=600, env=env
)
print("STDOUT:", result.stdout)
print("STDERR:", result.stderr[-3000:])
print("Return code:", result.returncode)

print("Return code:", result.returncode)

import os, subprocess
env = {**os.environ}
env['MUJOCO_PY_MUJOCO_PATH'] = '/root/.mujoco/mujoco210'
env['LD_LIBRARY_PATH'] = '/root/.mujoco/mujoco210/bin'
env['MUJOCO_GL'] = 'osmesa'
env['MPLBACKEND'] = 'Agg'
if 'LD_PRELOAD' in env: del env['LD_PRELOAD']

result = subprocess.run(
    ['/content/miniconda/envs/odt/bin/python', 'main.py',
     '--env', 'hopper-medium-v2',
     '--max_pretrain_iters', '1',
     '--num_updates_per_pretrain_iter', '100',
     '--max_online_iters', '10',
     '--num_online_rollouts', '1',
     '--num_eval_episodes', '1',
     '--device', 'cpu'],
    cwd='/content/online-dt',
    capture_output=True, text=True, timeout=600, env=env
)
print("STDOUT:", result.stdout)
print("STDERR:", result.stderr[-3000:])
print("Return code:", result.returncode)

print("Return code:", result.returncode)

print(result.stderr)

test_main = """
import sys
sys.path.insert(0, '/content/online-dt')
import os
os.environ['MUJOCO_PY_MUJOCO_PATH'] = '/root/.mujoco/mujoco210'
os.environ['LD_LIBRARY_PATH'] = '/root/.mujoco/mujoco210/bin'
os.environ['MUJOCO_GL'] = 'osmesa'
os.environ['MPLBACKEND'] = 'Agg'

print("1. imports...")
from torch.utils.tensorboard import SummaryWriter
import argparse, pickle, random, time, gym, d4rl, torch, numpy as np
import utils
from replay_buffer import ReplayBuffer
from lamb import Lamb
from stable_baselines3.common.vec_env import SubprocVecEnv
from data import create_dataloader
from decision_transformer.models.decision_transformer import DecisionTransformer
from evaluation import create_vec_eval_episodes_fn, vec_evaluate_episode_rtg
from trainer import SequenceTrainer
from logger import Logger
print("2. all imports OK!")

print("3. making env...")
env = gym.make('hopper-medium-v2')
print("4. env OK!", env)

print("5. loading dataset...")
dataset = env.get_dataset()
print("6. dataset OK! keys:", list(dataset.keys()))
"""
with open('/content/test_main.py', 'w') as f:
    f.write(test_main)

import os, subprocess
env = {**os.environ}
env['MUJOCO_PY_MUJOCO_PATH'] = '/root/.mujoco/mujoco210'
env['LD_LIBRARY_PATH'] = '/root/.mujoco/mujoco210/bin'
env['MUJOCO_GL'] = 'osmesa'
env['MPLBACKEND'] = 'Agg'
if 'LD_PRELOAD' in env: del env['LD_PRELOAD']

result = subprocess.run(
    ['/content/miniconda/envs/odt/bin/python', '/content/test_main.py'],
    capture_output=True, text=True, timeout=120, env=env
)
print("STDOUT:", result.stdout)
print("STDERR:", result.stderr[-2000:])
print("Return code:", result.returncode)

test_main2 = """
import sys
sys.path.insert(0, '/content/online-dt')
import os
os.environ['MUJOCO_PY_MUJOCO_PATH'] = '/root/.mujoco/mujoco210'
os.environ['LD_LIBRARY_PATH'] = '/root/.mujoco/mujoco210/bin'
os.environ['MUJOCO_GL'] = 'osmesa'
os.environ['MPLBACKEND'] = 'Agg'
os.environ['MUJOCO_PY_FORCE_CPU'] = '1'

import gym
import d4rl

print("making env...")
import mujoco_py
print("mujoco_py version:", mujoco_py.__version__)
env = gym.make('hopper-medium-v2')
print("env OK!")
"""
with open('/content/test_main2.py', 'w') as f:
    f.write(test_main2)

import os, subprocess
env = {**os.environ}
env['MUJOCO_PY_MUJOCO_PATH'] = '/root/.mujoco/mujoco210'
env['LD_LIBRARY_PATH'] = '/root/.mujoco/mujoco210/bin'
env['MUJOCO_GL'] = 'osmesa'
env['MPLBACKEND'] = 'Agg'
env['MUJOCO_PY_FORCE_CPU'] = '1'
if 'LD_PRELOAD' in env: del env['LD_PRELOAD']

result = subprocess.run(
    ['/content/miniconda/envs/odt/bin/python', '/content/test_main2.py'],
    capture_output=True, text=True, timeout=120, env=env
)
print("STDOUT:", result.stdout)
print("STDERR:", result.stderr[-2000:])
print("Return code:", result.returncode)

!find / -name "libGL.so*" 2>/dev/null | head -10
!find / -name "libOSMesa.so*" 2>/dev/null | head -10

import os, subprocess
env = {**os.environ}
env['MUJOCO_PY_MUJOCO_PATH'] = '/root/.mujoco/mujoco210'
env['LD_LIBRARY_PATH'] = '/root/.mujoco/mujoco210/bin:/usr/lib/x86_64-linux-gnu'
env['MUJOCO_GL'] = 'osmesa'
env['MPLBACKEND'] = 'Agg'
env['LD_PRELOAD'] = '/usr/lib/x86_64-linux-gnu/libOSMesa.so'
if 'LD_PRELOAD' in env: env['LD_PRELOAD'] = '/usr/lib/x86_64-linux-gnu/libOSMesa.so'

result = subprocess.run(
    ['/content/miniconda/envs/odt/bin/python', '/content/test_main2.py'],
    capture_output=True, text=True, timeout=120, env=env
)
print("STDOUT:", result.stdout)
print("STDERR:", result.stderr[-2000:])
print("Return code:", result.returncode)

# gym এর hopper environment কে নতুন mujoco দিয়ে চালাবো
!/content/miniconda/envs/odt/bin/pip install gymnasium gymnasium-mujoco 2>&1 | tail -5

patch = """
import sys
sys.path.insert(0, '/content/online-dt')
import os
os.environ['MUJOCO_GL'] = 'osmesa'
os.environ['MPLBACKEND'] = 'Agg'

import unittest.mock as mock
sys.modules['mujoco_py'] = mock.MagicMock()

import gym
import d4rl
print("making env...")
env = gym.make('hopper-medium-v2')
print("env OK!", env)
"""
with open('/content/test_patch.py', 'w') as f:
    f.write(patch)

import os, subprocess
env = {**os.environ}
env['MUJOCO_GL'] = 'osmesa'
env['MPLBACKEND'] = 'Agg'
if 'LD_PRELOAD' in env: del env['LD_PRELOAD']

result = subprocess.run(
    ['/content/miniconda/envs/odt/bin/python', '/content/test_patch.py'],
    capture_output=True, text=True, timeout=120, env=env
)
print("STDOUT:", result.stdout)
print("STDERR:", result.stderr[-2000:])
print("Return code:", result.returncode)

print("Return code:", result.returncode)

print(result.stderr)

!/content/miniconda/envs/odt/bin/pip install numpy==1.21.0 --force-reinstall 2>&1 | tail -5

import os, subprocess
env = {**os.environ}
env['MUJOCO_PY_MUJOCO_PATH'] = '/root/.mujoco/mujoco210'
env['LD_LIBRARY_PATH'] = '/root/.mujoco/mujoco210/bin'
env['MUJOCO_GL'] = 'osmesa'
env['MPLBACKEND'] = 'Agg'
if 'LD_PRELOAD' in env: del env['LD_PRELOAD']

result = subprocess.run(
    ['/content/miniconda/envs/odt/bin/python', '/content/test_patch.py'],
    capture_output=True, text=True, timeout=120, env=env
)
print("STDOUT:", result.stdout)
print("STDERR:", result.stderr[-2000:])
print("Return code:", result.returncode)

import os, subprocess

env = {
    'MUJOCO_PY_MUJOCO_PATH': '/root/.mujoco/mujoco210',
    'LD_LIBRARY_PATH': '/root/.mujoco/mujoco210/bin:/usr/lib/x86_64-linux-gnu',
    'MUJOCO_GL': 'osmesa',
    'MPLBACKEND': 'Agg',
    'PYOPENGL_PLATFORM': 'osmesa',
    'PATH': os.environ.get('PATH', ''),
    'HOME': '/root',
    'PYTHONPATH': '/content/online-dt'
}

result = subprocess.run(
    ['/content/miniconda/envs/odt/bin/python', '/content/test_patch.py'],
    capture_output=True, text=True, timeout=120, env=env
)
print("STDOUT:", result.stdout)
print("STDERR:", result.stderr[-3000:])
print("Return code:", result.returncode)

!/content/miniconda/envs/odt/bin/pip install gymnasium[mujoco] 2>&1 | tail -5

test = """
import os
os.environ['MUJOCO_GL'] = 'osmesa'
import gymnasium as gym
env = gym.make('Hopper-v4')
obs, info = env.reset()
print('ENV OK! obs shape:', obs.shape)
"""
with open('/content/test_gym2.py', 'w') as f:
    f.write(test)

import os, subprocess
env = {**os.environ}
env['MUJOCO_GL'] = 'osmesa'
env['MPLBACKEND'] = 'Agg'
if 'LD_PRELOAD' in env: del env['LD_PRELOAD']

result = subprocess.run(
    ['/content/miniconda/envs/odt/bin/python', '/content/test_gym2.py'],
    capture_output=True, text=True, timeout=120, env=env
)
print("STDOUT:", result.stdout)
print("STDERR:", result.stderr[-2000:])
print("Return code:", result.returncode)

content = open('/content/online-dt/main.py').read()
content = content.replace('import gym', 'import gymnasium as gym')
content = content.replace('import d4rl', '#import d4rl')
open('/content/online-dt/main.py', 'w').write(content)
print("main.py patched!")

content = open('/content/online-dt/data.py').read()
content = content.replace('import gym', 'import gymnasium as gym')
content = content.replace('import d4rl', '#import d4rl')
open('/content/online-dt/data.py', 'w').write(content)
print("data.py patched!")

import os, subprocess
env = {**os.environ}
env['MUJOCO_GL'] = 'osmesa'
env['MPLBACKEND'] = 'Agg'
if 'LD_PRELOAD' in env: del env['LD_PRELOAD']

result = subprocess.run(
    ['/content/miniconda/envs/odt/bin/python', 'main.py',
     '--env', 'Hopper-v4',
     '--max_pretrain_iters', '1',
     '--num_updates_per_pretrain_iter', '100',
     '--max_online_iters', '10',
     '--num_online_rollouts', '1',
     '--num_eval_episodes', '1',
     '--device', 'cpu'],
    cwd='/content/online-dt',
    capture_output=True, text=True, timeout=600, env=env
)
print("STDOUT:", result.stdout)
print("STDERR:", result.stderr[-3000:])
print("Return code:", result.returncode)

!/content/miniconda/envs/odt/bin/pip install numpy==1.23.5 --force-reinstall 2>&1 | tail -5

import os, subprocess
env = {**os.environ}
env['MUJOCO_GL'] = 'osmesa'
env['MPLBACKEND'] = 'Agg'
if 'LD_PRELOAD' in env: del env['LD_PRELOAD']

result = subprocess.run(
    ['/content/miniconda/envs/odt/bin/python', 'main.py',
     '--env', 'Hopper-v4',
     '--max_pretrain_iters', '1',
     '--num_updates_per_pretrain_iter', '100',
     '--max_online_iters', '10',
     '--num_online_rollouts', '1',
     '--num_eval_episodes', '1',
     '--device', 'cpu'],
    cwd='/content/online-dt',
    capture_output=True, text=True, timeout=600, env=env
)
print("STDOUT:", result.stdout)
print("STDERR:", result.stderr[-3000:])
print("Return code:", result.returncode)

import os, subprocess
env = {**os.environ}
env['MUJOCO_GL'] = 'osmesa'
env['MPLBACKEND'] = 'Agg'
if 'LD_PRELOAD' in env: del env['LD_PRELOAD']

result = subprocess.run(
    ['/content/miniconda/envs/odt/bin/python',
     'data/download_d4rl_gym_datasets.py'],
    cwd='/content/online-dt',
    capture_output=True, text=True, timeout=600, env=env
)
print("STDOUT:", result.stdout)
print("STDERR:", result.stderr[-3000:])
print("Return code:", result.returncode)

import os, subprocess
env = {**os.environ}
env['MUJOCO_PY_MUJOCO_PATH'] = '/root/.mujoco/mujoco210'
env['LD_LIBRARY_PATH'] = '/root/.mujoco/mujoco210/bin'
env['MUJOCO_GL'] = 'osmesa'
env['MPLBACKEND'] = 'Agg'
if 'LD_PRELOAD' in env: del env['LD_PRELOAD']

script = """
import os
os.environ['MUJOCO_GL'] = 'osmesa'
os.environ['MPLBACKEND'] = 'Agg'
import gymnasium as gym
import numpy as np
import pickle

print("Creating Hopper-v4 dataset...")
env = gym.make('Hopper-v4')

trajectories = []
for ep in range(50):
    obs, _ = env.reset()
    states, actions, rewards, dones = [], [], [], []
    for t in range(1000):
        action = env.action_space.sample()
        next_obs, reward, terminated, truncated, _ = env.step(action)
        states.append(obs)
        actions.append(action)
        rewards.append(reward)
        done = terminated or truncated
        dones.append(done)
        obs = next_obs
        if done:
            break
    trajectories.append({
        'observations': np.array(states),
        'actions': np.array(actions),
        'rewards': np.array(rewards),
        'dones': np.array(dones),
    })
    print(f"Episode {ep+1}/50 done, length: {len(states)}")

os.makedirs('./data', exist_ok=True)
with open('./data/Hopper-v4.pkl', 'wb') as f:
    pickle.dump(trajectories, f)
print("Dataset saved!")
"""
with open('/content/create_dataset.py', 'w') as f:
    f.write(script)

result = subprocess.run(
    ['/content/miniconda/envs/odt/bin/python', '/content/create_dataset.py'],
    cwd='/content/online-dt',
    capture_output=True, text=True, timeout=300, env=env
)
print("STDOUT:", result.stdout)
print("STDERR:", result.stderr[-2000:])
print("Return code:", result.returncode)

import os, subprocess
env = {**os.environ}
env['MUJOCO_GL'] = 'osmesa'
env['MPLBACKEND'] = 'Agg'
if 'LD_PRELOAD' in env: del env['LD_PRELOAD']

result = subprocess.run(
    ['/content/miniconda/envs/odt/bin/python', 'main.py',
     '--env', 'Hopper-v4',
     '--max_pretrain_iters', '1',
     '--num_updates_per_pretrain_iter', '100',
     '--max_online_iters', '10',
     '--num_online_rollouts', '1',
     '--num_eval_episodes', '1',
     '--device', 'cpu'],
    cwd='/content/online-dt',
    capture_output=True, text=True, timeout=600, env=env
)
print("STDOUT:", result.stdout)
print("STDERR:", result.stderr[-3000:])
print("Return code:", result.returncode)

content = open('/content/online-dt/decision_transformer/models/trajectory_gpt2.py').read()
content = content.replace('config.n_ctx', 'config.n_positions')
open('/content/online-dt/decision_transformer/models/trajectory_gpt2.py', 'w').write(content)
print("Fixed!")

import os, subprocess
env = {**os.environ}
env['MUJOCO_GL'] = 'osmesa'
env['MPLBACKEND'] = 'Agg'
if 'LD_PRELOAD' in env: del env['LD_PRELOAD']

result = subprocess.run(
    ['/content/miniconda/envs/odt/bin/python', 'main.py',
     '--env', 'Hopper-v4',
     '--max_pretrain_iters', '1',
     '--num_updates_per_pretrain_iter', '100',
     '--max_online_iters', '10',
     '--num_online_rollouts', '1',
     '--num_eval_episodes', '1',
     '--device', 'cpu'],
    cwd='/content/online-dt',
    capture_output=True, text=True, timeout=600, env=env
)
print("STDOUT:", result.stdout)
print("STDERR:", result.stderr[-3000:])
print("Return code:", result.returncode)

content = open('/content/online-dt/main.py').read()
content = content.replace(
    'env.seed(seed)',
    'pass  # env.seed(seed) not needed in gymnasium'
)
content = content.replace(
    'elif hasattr(env.env, "seed"):\n                    env.env.seed(seed)',
    'pass'
)
open('/content/online-dt/main.py', 'w').write(content)
print("Fixed!")

import os, subprocess
env = {**os.environ}
env['MUJOCO_GL'] = 'osmesa'
env['MPLBACKEND'] = 'Agg'
if 'LD_PRELOAD' in env: del env['LD_PRELOAD']

result = subprocess.run(
    ['/content/miniconda/envs/odt/bin/python', 'main.py',
     '--env', 'Hopper-v4',
     '--max_pretrain_iters', '1',
     '--num_updates_per_pretrain_iter', '100',
     '--max_online_iters', '10',
     '--num_online_rollouts', '1',
     '--num_eval_episodes', '1',
     '--device', 'cpu'],
    cwd='/content/online-dt',
    capture_output=True, text=True, timeout=600, env=env
)
print("STDOUT:", result.stdout)
print("STDERR:", result.stderr[-3000:])
print("Return code:", result.returncode)

content = open('/content/online-dt/main.py').read()

# সব seed related lines fix করো
import re
content = re.sub(r'env\.seed\(seed\)', 'pass', content)
content = re.sub(r'env\.env\.seed\(seed\)', 'pass', content)
content = re.sub(r'env\.action_space\.seed\(seed\)', 'pass', content)
content = re.sub(r'env\.observation_space\.seed\(seed\)', 'pass', content)

open('/content/online-dt/main.py', 'w').write(content)
print("Fixed!")

# verify
!grep -n "seed" /content/online-dt/main.py

content = open('/content/online-dt/main.py').read()
print(content[content.find('def get_env_builder'):content.find('def get_env_builder')+600])

content = open('/content/online-dt/main.py').read()

old = """def get_env_builder(seed, env_name, target_goal=None):
            def make_env_fn():
                #import d4rl
                env = gym.make(env_name)
                pass  # pass not needed in gymnasium
                if hasattr(env.env, "wrapped_env"):
                    env.env.wrapped_pass  # pass not needed in gymnasium
                elif hasattr(env.env, "seed"):
                    env.pass  # pass not needed in gymnasium
                else:
                    pass
                pass
                pass"""

new = """def get_env_builder(seed, env_name, target_goal=None):
            def make_env_fn():
                env = gym.make(env_name)"""

content = content.replace(old, new)
open('/content/online-dt/main.py', 'w').write(content)
print("Fixed!")
!grep -n "seed" /content/online-dt/main.py

lines = open('/content/online-dt/main.py').readlines()
for i, line in enumerate(lines[410:430], start=411):
    print(f"{i}: {line}", end='')

lines = open('/content/online-dt/main.py').readlines()

new_lines = []
skip = False
for i, line in enumerate(lines):
    if 'pass  # pass not needed in gymnasium' in line:
        continue
    if 'if hasattr(env.env, "wrapped_env"):' in line:
        skip = True
    if skip and 'if target_goal:' in line:
        skip = False
    if not skip:
        new_lines.append(line)

open('/content/online-dt/main.py', 'w').write(''.join(new_lines))
print("Fixed!")

# verify
lines = open('/content/online-dt/main.py').readlines()
for i, line in enumerate(lines[410:435], start=411):
    print(f"{i}: {line}", end='')

import os

os.environ['MUJOCO_GL'] = 'osmesa'
os.environ['MPLBACKEND'] = 'Agg'

!cd /content/online-dt && \
  MUJOCO_GL=osmesa MPLBACKEND=Agg \
  /content/miniconda/envs/odt/bin/python main.py \
  --env Hopper-v4 \
  --max_pretrain_iters 1 \
  --num_updates_per_pretrain_iter 50 \
  --max_online_iters 3 \
  --num_online_rollouts 1 \
  --num_eval_episodes 1 \
  --device cpu